"""
TripSaathi API Schemas
========================
Pydantic models for API request and response validation.

WHY PYDANTIC MODELS FOR APIS?
------------------------------
FastAPI uses Pydantic models to:
1. Validate incoming requests (wrong type? missing field? → automatic 422 error)
2. Serialize responses (convert Python objects to JSON)
3. Generate OpenAPI/Swagger documentation automatically
4. Provide IDE autocompletion and type safety

INTERVIEW QUESTIONS:
- Q: "What happens when a request body doesn't match the Pydantic model?"
  A: FastAPI automatically returns a 422 Unprocessable Entity response
     with a detailed error listing which fields failed validation.

- Q: "Why use separate Request and Response models?"
  A: The request only needs user input (destination, days, etc.).
     The response includes computed data (itinerary, budget breakdown).
     Separating them keeps each model focused and prevents data leakage.
"""

from pydantic import BaseModel, Field


# ============================================================
# Request Model
# ============================================================

class TripRequest(BaseModel):
    """
    Request body for POST /api/trip/plan
    
    Example:
    {
        "destination": "Jaipur",
        "days": 3,
        "travelers": 2,
        "budget": 15000,
        "preferences": ["history", "food", "photography"]
    }
    """
    destination: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Travel destination name",
        examples=["Jaipur"],
    )
    days: int = Field(
        ...,
        ge=1,
        le=14,
        description="Number of travel days (1-14)",
        examples=[3],
    )
    travelers: int = Field(
        ...,
        ge=1,
        le=20,
        description="Number of travelers (1-20)",
        examples=[2],
    )
    budget: float = Field(
        ...,
        gt=0,
        description="Total budget in INR",
        examples=[15000],
    )
    preferences: list[str] = Field(
        default=[],
        max_length=10,
        description="User preferences/interests",
        examples=[["history", "food", "photography"]],
    )


# ============================================================
# Response Models
# ============================================================

class TripResponse(BaseModel):
    """
    Response body for POST /api/trip/plan
    
    Contains the complete trip plan generated by the multi-agent workflow.
    """
    trip_id: str = Field(description="Unique trip identifier")
    destination: str = Field(description="Trip destination")
    days: int = Field(description="Number of days")
    travelers: int = Field(description="Number of travelers")

    total_estimated_cost: float = Field(description="Total estimated cost in INR")
    within_budget: bool = Field(description="Whether the trip is within budget")

    itinerary: dict = Field(description="Day-by-day itinerary")
    budget_breakdown: dict = Field(description="Detailed cost breakdown")
    critique: dict = Field(description="Quality review results")

    recommendations: list[str] = Field(
        default=[], description="General trip recommendations"
    )
    sources: list[str] = Field(
        default=[], description="RAG sources used for information"
    )

    status: str = Field(description="Workflow status: approved, rejected, max_revisions_reached")
    revision_count: int = Field(description="Number of revisions made")


class ErrorResponse(BaseModel):
    """Standard error response."""
    detail: str = Field(description="Error description")
    error_code: str = Field(default="INTERNAL_ERROR", description="Error code")
